---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FernandoBittencourt/Microservices-With-Spring-Student-Files
server:
  port: 8001
management:
  security:
    enabled: false
