# Note: all properties defined in this file are subject to replacement by the configuration server.
---
words: fallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
